{% set version = "0.7.1" %}
{% set sha256 = "674a70c645b773a02a416ebc3ea802b7fb45613a0595ca5f26fc4dad15ca77b8" %}

package:
  name: datreant.data
  version: {{ version }}

source:
  fn: datreant.data-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/datreant.data/datreant.data-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - datreant <=1.0
    - datreant.core
    - numpy
    - pandas
    - six
    - pytables
    - h5py

test:
  imports:
    - datreant.data
  requires:
    - pytest

about:
  home: http://datreant.org/
  license: BSD 3-Clause
  summary: 'persistent, pythonic trees for heterogeneous data'

extra:
  recipe-maintainers:
    - dotsdl
    - kain88-de
