appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gwFlfNG6kHGWQpq1DcYQbGejQZ36xy+us2vz049yjDHCqFF4ZxWO5piLxVvJXn2Nib+j14oquQeAIZx7+IODh22Pq1UYUEYxnP4JfjPQk914p+4Xq8+czMYlsYGnG2r7lCpeOhw1sibKPVJydXbSvnd/WMhyUaQ74M+cjkIbg6sGiTZxl0/n2JmjisQjDyMAx2Se+wFPoH0jhpftHabD80kuvYZY/WtDHDqj+WVwdpNmKrCevLUnbiVr8muKTxLjfnkwXkgElMg0JysKSrk9PH7PbikCBc47c08pre/ZCRFgQqPUQAXsqp0M3POXIsMbBlDyFY1Yb7SMPnDjsJ8+yf4aGERjmuJRWz0uZx0ttd/1DWll50qu4lAz1r4p7FKb9kY5KA4EqufDYunCjloLO1Da+3nvhcgRTKVXI4EOjqUKvXFQcEtE4BonYkwJPOy/nfmduAf0BbtijAnhQd28D9MGnaJIX/h7pSUxXqnML49pX/UENf1Iu2PeGx2VB802SEpmJCeE0Bt+VRQAwv4+4eNGkyCKO+Oc24YyVobhcOTLFgkk8ezhHuobEi16l1FZD3qx4nW1K8MH+ZTJkI1qIJbaIBaXgbEk4mYUGPO7gr8GAC5+OayqoFED6bO1UFbjSL2qScSNzKGAFoT6IekI91H89KcElbF/0wIqHeYAefY=}
